[package]
name = "advent_of_code_2024"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "day_1"

[[bin]]
name = "day_2"

[[bin]]
name = "day_3"

[[bin]]
name = "day_4"

[[bin]]
name = "day_5"

[dependencies]
